modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="unlocked_forge"
version="1.0.0"
displayName="Unlocked Forge"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="espen, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.unlocked_forge]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



